import time

import pytest

from pageObjects.agentLoginPage import agentLogin
from pageObjects.AgentCDPostpaidGuestNewRegistration import AgentPostPaidNewRegistration
from pageObjects.CDPostpaidGuestNewRegistration import PostPaidNewRegistration
from Utilities.readProperties import ReadConfig


class Test_NewRegistrationAgentLogin:
    agentURL = ReadConfig.getAgentURL()
    username = ReadConfig.getAgentUsername()
    password = ReadConfig.getAgentPassword()
    idNumber = ReadConfig.getIDNumber()
    fullName = ReadConfig.getFullName()
    line1 = ReadConfig.getLine1()
    line2 = ReadConfig.getLine2()
    postcode = ReadConfig.getPostCode()
    city = ReadConfig.getCity()
    dline1 = ReadConfig.getDLine1()
    dline2 = ReadConfig.getDLine2()
    dPostcode = ReadConfig.getDPostCode()
    dCity = ReadConfig.getDCity()
    mobileNumber = ReadConfig.getMobileNumber()
    email = ReadConfig.getEmail()

    @pytest.mark.sanity
    def test_AgentPostPaidNewRegistration(self, setup):
        self.driver = setup
        self.driver.get(self.agentURL)
        self.AL = agentLogin(self.driver)
        self.AL.clickTeleSalesButton()
        self.AL.enterAgentUsername(self.username)
        self.AL.clickOnNextButton()
        time.sleep(2)
        self.AL.enterAgentPassword(self.password)
        self.AL.clickSingIn()
        time.sleep(1)
        self.AL.clickYesButton()
        time.sleep(5)
        self.pPNRA = AgentPostPaidNewRegistration(self.driver)
        self.pPNR = PostPaidNewRegistration(self.driver)
        self.pPNRA.clickBuyButton()
        # self.pPNRA.clickSelectPlanDropDown()
        time.sleep(2)
        self.pPNRA.selectCDPostPaidPlan()
        time.sleep(2)
        # time.sleep(1)
        self.pPNRA.clickPlanOptionDropDown()
        time.sleep(1)
        self.pPNRA.selectPlanValue()
        time.sleep(1)
        self.pPNRA.clickNextButton()
        # time.sleep(10)
        # self.pPNR.clickRadioButton()
        self.pPNR.enterIDNumber(self.idNumber)
        self.pPNR.clickSubmitButton()
        self.pPNR.clickSelectNumber()
        self.pPNR.clickCheckOutButton()
        time.sleep(10)
        self.pPNRA.enterLine1(self.line1)
        self.pPNRA.enterLine2(self.line2)
        self.pPNRA.enterPostcode(self.postcode)
        self.pPNRA.enterCity(self.city)
        # self.pPNR.clickUploadButton()
        # self.pPNR.clickPopupUploadButton1()
        time.sleep(2)
        # self.pPNR.clickUploadButton()
        time.sleep(2)
        # self.pPNR.clickUploadSelfieButton()
        # self.pPNR.clickPopupUploadButton2()
        # self.pPNR.clickSaveButton()
        # self.pPNR.enterFullName(self.fullName)
        # self.pPNR.enterLine1(self.line1)
        # self.pPNR.enterLine2(self.line2)
        # self.pPNR.enterPostcode(self.postcode)
        # self.pPNR.enterCity(self.city)
        # self.pPNR.selectStateValue()
        self.pPNR.clickSaveButton()
        self.pPNR.clickYouIDDetailsYes()
        # self.pPNR.enterEmailID(self.email)
        self.pPNR.enterDLine1(self.dline1)
        self.pPNR.enterDLine2(self.dline2)
        self.pPNR.enterDPostcode(self.dPostcode)
        self.pPNR.enterDCity(self.dCity)
        self.pPNR.enterMobileNumber(self.mobileNumber)
        self.pPNR.clickDSaveButton()
